version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    container_name: news_stocks_backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    container_name: news_stocks_frontend
